### ISSUE TITLE
How do I run/compile one of your examples?

### ISSUE THREAD

**Issue by xylo** [shogowada/scalajs-reactjs#37]
Can you add some hints how to run/compile one of your example projects?

**Comment by viktor-podzigun** [comment]
@xylo you could try the following:
* first, build the project with the command: `sbt fastOptJS::webpack`
* then open one of example's `index.html` file from `target` folder of your choice:
```
open ./example/helloworld/target/scala-2.12/classes/index.html
#or:
open ./example/router/target/scala-2.12/classes/index.html
```
Hope this helps.

**Comment by shogowada** [comment]
@viktor-podzigun Thanks! And sorry for missing this issue for such a long time, @xylo.

I don't think I can no longer maintain this repository. I just added a warning to the [README](https://github.com/shogowada/scalajs-reactjs/blob/master/README.md).

**Comment by shogowada** [comment]
Closing as the support is moved to https://github.com/scommons/scalajs-reactjs
